# Generated by Django 2.1 on 2021-11-18 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary_diet',
            name='image_count',
        ),
    ]
