# Generated by Django 2.1 on 2021-02-22 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0002_auto_20210222_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_pressure',
            name='recorded_at',
            field=models.DateTimeField(blank=True),
        ),
    ]
