# Generated by Django 2.1 on 2021-02-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0004_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blood_pressure',
            name='recorded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
