# Generated by Django 2.1 on 2021-02-26 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0006_auto_20210224_0625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood_sugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('sugar', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True)),
                ('timeperiod', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=5, null=True)),
                ('recorded_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
