# Generated by Django 2.1 on 2021-03-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0009_diary_diet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary_diet',
            name='image_count',
        ),
        migrations.AlterField(
            model_name='diary_diet',
            name='recorded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
