# Generated by Django 2.1 on 2021-03-15 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0010_auto_20210310_0650'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diary_diet',
        ),
    ]
