# Generated by Django 2.1 on 2021-03-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0011_delete_diary_diet'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('member_id', models.CharField(blank=True, max_length=100)),
                ('reply_id', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
