# Generated by Django 2.1 on 2021-03-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('body', '0012_usercare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercare',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
