# Generated by Django 2.1 on 2021-03-15 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend_data',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='friend_data',
            name='recorded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
