# Generated by Django 2.1 on 2021-03-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0002_auto_20210315_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend_data',
            name='imread',
            field=models.BooleanField(default=True),
        ),
    ]
