# Generated by Django 2.1 on 2021-03-15 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friend', '0003_auto_20210315_0144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend_data',
            old_name='recorded_at',
            new_name='updated_at',
        ),
    ]
