# Generated by Django 2.1 on 2021-02-01 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('Type', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('recorded_at', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HbA1c',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('a1c', models.CharField(blank=True, max_length=8)),
                ('recorded_at', models.CharField(blank=True, max_length=8)),
                ('ids', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_Information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('disabetes_type', models.CharField(blank=True, max_length=100)),
                ('oad', models.BooleanField(default=True)),
                ('insulin', models.BooleanField(default=True)),
                ('anti_hypertensives', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('account', models.CharField(blank=True, max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invite_code', models.CharField(max_length=100, null=True)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('emailck', models.BooleanField(default=True)),
                ('FBck', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('birthday', models.CharField(blank=True, max_length=8)),
                ('height', models.CharField(blank=True, max_length=30)),
                ('gender', models.BooleanField(default=True)),
                ('fcm_id', models.CharField(max_length=30)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('weight', models.CharField(blank=True, max_length=30)),
                ('phone', models.CharField(blank=True, max_length=100)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('sugar_delta_max', models.IntegerField(blank=True, default=0)),
                ('sugar_delta_min', models.IntegerField(blank=True, default=0)),
                ('sugar_morning_max', models.IntegerField(blank=True, default=0)),
                ('sugar_morning_min', models.IntegerField(blank=True, default=0)),
                ('sugar_evening_max', models.IntegerField(blank=True, default=0)),
                ('sugar_evening_min', models.IntegerField(blank=True, default=0)),
                ('sugar_before_max', models.IntegerField(blank=True, default=0)),
                ('sugar_before_min', models.IntegerField(blank=True, default=0)),
                ('sugar_after_max', models.IntegerField(blank=True, default=0)),
                ('sugar_after_min', models.IntegerField(blank=True, default=0)),
                ('systolic_max', models.IntegerField(blank=True, default=0)),
                ('systolic_min', models.IntegerField(blank=True, default=0)),
                ('diastolic_max', models.IntegerField(blank=True, default=0)),
                ('diastolic_min', models.IntegerField(blank=True, default=0)),
                ('pulse_max', models.IntegerField(blank=True, default=0)),
                ('pulse_min', models.IntegerField(blank=True, default=0)),
                ('weight_max', models.IntegerField(blank=True, default=0)),
                ('weight_min', models.IntegerField(blank=True, default=0)),
                ('bmi_max', models.IntegerField(blank=True, default=0)),
                ('bmi_min', models.IntegerField(blank=True, default=0)),
                ('body_fat_max', models.IntegerField(blank=True, default=0)),
                ('body_fat_min', models.IntegerField(blank=True, default=0)),
                ('after_recording', models.BooleanField(default=True)),
                ('no_recording_for_a_day', models.BooleanField(default=True)),
                ('over_max_or_under_min', models.BooleanField(default=True)),
                ('after_meal', models.BooleanField(default=True)),
                ('unit_of_sugar', models.BooleanField(default=True)),
                ('unit_of_weight', models.BooleanField(default=True)),
                ('unit_of_height', models.BooleanField(default=True)),
            ],
        ),
    ]
