# Generated by Django 2.1 on 2021-02-03 07:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210203_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fb_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
