# Generated by Django 2.1 on 2021-02-03 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_userprofile_fb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical_information',
            name='disabetes_type',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
