# Generated by Django 2.1 on 2021-02-03 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20210203_0745'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical_information',
            name='disabetes_type',
        ),
        migrations.AddField(
            model_name='medical_information',
            name='diabetes_type',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15),
        ),
    ]
