# Generated by Django 2.1 on 2021-02-03 08:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210203_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='drug_information',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drug_information',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='drug_information',
            name='Type',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='drug_information',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
