# Generated by Django 2.1 on 2021-02-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20210203_0832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HbA1c',
        ),
        migrations.AddField(
            model_name='medical_information',
            name='a1c',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=2),
        ),
    ]
