# Generated by Django 2.1 on 2021-02-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210203_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug_information',
            name='recorded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
