# Generated by Django 2.1 on 2021-02-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20210214_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug_information',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
