# Generated by Django 2.1 on 2021-02-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20210214_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug_information',
            name='Type',
            field=models.BooleanField(default=True),
        ),
    ]
