# Generated by Django 2.1 on 2021-02-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20210217_1544'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drug_Information',
            new_name='druginformation',
        ),
    ]
