# Generated by Django 2.1 on 2021-02-24 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20210224_0642'),
    ]

    operations = [
        migrations.RenameField(
            model_name='druginformation',
            old_name='name',
            new_name='drugname',
        ),
        migrations.RenameField(
            model_name='druginformation',
            old_name='Type',
            new_name='drugtype',
        ),
        migrations.AlterField(
            model_name='druginformation',
            name='recorded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
