# Generated by Django 2.1 on 2021-03-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20210224_0656'),
    ]

    operations = [
        migrations.AddField(
            model_name='userset',
            name='must_change_password',
            field=models.BooleanField(default=True),
        ),
    ]
