# Generated by Django 2.1 on 2021-04-09 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_share'),
    ]

    operations = [
        migrations.AddField(
            model_name='userset',
            name='badge',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=15),
        ),
        migrations.AddField(
            model_name='userset',
            name='group',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
