# Generated by Django 2.1 on 2021-04-09 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20210409_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='userset',
            name='pushed_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
