# Generated by Django 2.1 on 2021-04-09 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_userset_pushed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userset',
            name='birthday',
            field=models.DateField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='userset',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2, max_length=30),
        ),
        migrations.AlterField(
            model_name='userset',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=2, max_length=30),
        ),
    ]
